### ISSUE TITLE
Recast nav mesh verticies go outside bounding box?

### ISSUE THREAD

**Issue by LiamKarlMitchell** [recastnavigation/recastnavigation#290] opened 2017-11-08 13:52 UTC
Overview of the Issue: Navmesh generation has high walls.

It seems with some inputs, the navmesh has points outside the shown bounding box in the Recast Demo application. Which is odd because the input mesh does not have points up there.

Windows 7, VS 2017

The agents do navigate over this spot briefly and go very high up.
The height is larger than Max Climb of 10.0 so why does it exist?

Callstack: N/A
Screenshots: (Have not figured out debug draw yet sorry)

![image](https://user-images.githubusercontent.com/1968109/32548913-5e65eebc-c4ec-11e7-9cc4-d6dc99a63704.png)

![image](https://user-images.githubusercontent.com/1968109/32553137-e17befc8-c4fa-11e7-8965-b34bb4fb5e2b.png)

Logs:
Reproduction steps:
I supply an example gset and mesh.
[Example.zip](https://github.com/recastnavigation/recastnavigation/files/1454086/Example.zip)

Interestingly changing tiles off 80 can make it go away.
Decreasing the Max edge Error can make it go away.
But it can still show up in other scenarios/meshes.
Note: It is possible that the mesh data is wrong/bad.

Recast version(s) and/or git commit hash: 2c85309280dbc9c82029e7ab16dfb01b9235c74e
Environment: Windows 7, 

VS 2017
Related issues: 
Suggest a Fix:

I wonder if this is caused by overflow or signed/unsigned mismatch.

So I compiled with optimization and higher warning level.
```
------ Rebuild All started: Project: Recast, Configuration: Release Win32 ------
Recast.cpp
recastnavigation\Recast\Include\Recast.h(174): warning C4820: 'rcContext': '2' bytes padding added after data member 'rcContext::m_timerEnabled'
recastnavigation\Recast\Include\Recast.h(392): warning C4820: 'rcContour': '1' bytes padding added after data member 'rcContour::area'
recastnavigation\Recast\Include\Recast.h(1075): warning C4365: 'return': conversion from 'unsigned int' to 'int', signed/unsigned mismatch
..\..\..\Recast\Source\Recast.cpp(401): warning C4365: '=': conversion from 'int' to 'unsigned int', signed/unsigned mismatch
..\..\..\Recast\Source\Recast.cpp(448): warning C4365: 'initializing': conversion from 'unsigned int' to 'int', signed/unsigned mismatch
..\..\..\Recast\Source\Recast.cpp(448): warning C4365: 'initializing': conversion from 'unsigned int' to 'const int', signed/unsigned mismatch
RecastAlloc.cpp
RecastArea.cpp
recastnavigation\Recast\Include\Recast.h(174): warning C4820: 'rcContext': '2' bytes padding added after data member 'rcContext::m_timerEnabled'
recastnavigation\Recast\Include\Recast.h(392): warning C4820: 'rcContour': '1' bytes padding added after data member 'rcContour::area'
recastnavigation\Recast\Include\Recast.h(1075): warning C4365: 'return': conversion from 'unsigned int' to 'int', signed/unsigned mismatch
RecastAssert.cpp
RecastContour.cpp
recastnavigation\Recast\Include\Recast.h(174): warning C4820: 'rcContext': '2' bytes padding added after data member 'rcContext::m_timerEnabled'
recastnavigation\Recast\Include\Recast.h(392): warning C4820: 'rcContour': '1' bytes padding added after data member 'rcContour::area'
recastnavigation\Recast\Include\Recast.h(1075): warning C4365: 'return': conversion from 'unsigned int' to 'int', signed/unsigned mismatch
..\..\..\Recast\Source\RecastContour.cpp(41): warning C4365: '=': conversion from 'int' to 'unsigned int', signed/unsigned mismatch
..\..\..\Recast\Source\RecastContour.cpp(50): warning C4365: '=': conversion from 'int' to 'unsigned int', signed/unsigned mismatch
..\..\..\Recast\Source\RecastContour.cpp(58): warning C4365: '=': conversion from 'int' to 'unsigned int', signed/unsigned mismatch
..\..\..\Recast\Source\RecastContour.cpp(68): warning C4365: '=': conversion from 'int' to 'unsigned int', signed/unsigned mismatch
..\..\..\Recast\Source\RecastContour.cpp(76): warning C4365: '=': conversion from 'int' to 'unsigned int', signed/unsigned mismatch
..\..\..\Recast\Source\RecastContour.cpp(156): warning C4365: '=': conversion from 'int' to 'unsigned char', signed/unsigned mismatch
..\..\..\Recast\Source\RecastContour.cpp(177): warning C4365: '=': conversion from 'int' to 'unsigned char', signed/unsigned mismatch
..\..\..\Recast\Source\RecastContour.cpp(728): warning C4365: 'argument': conversion from 'int' to '::size_t', signed/unsigned mismatch
..\..\..\Recast\Source\RecastContour.cpp(774): warning C4365: 'argument': conversion from 'int' to '::size_t', signed/unsigned mismatch
..\..\..\Recast\Source\RecastContour.cpp(897): warning C4365: '=': conversion from 'int' to 'unsigned char', signed/unsigned mismatch
RecastFilter.cpp
recastnavigation\Recast\Include\Recast.h(174): warning C4820: 'rcContext': '2' bytes padding added after data member 'rcContext::m_timerEnabled'
recastnavigation\Recast\Include\Recast.h(392): warning C4820: 'rcContour': '1' bytes padding added after data member 'rcContour::area'
recastnavigation\Recast\Include\Recast.h(1075): warning C4365: 'return': conversion from 'unsigned int' to 'int', signed/unsigned mismatch
..\..\..\Recast\Source\RecastFilter.cpp(111): warning C4365: 'initializing': conversion from 'unsigned int' to 'int', signed/unsigned mismatch
..\..\..\Recast\Source\RecastFilter.cpp(112): warning C4365: 'initializing': conversion from 'unsigned int' to 'int', signed/unsigned mismatch
recastnavigation\Recast\Include\Recast.h(174): warning C4820: 'rcContext': '2' bytes padding added after data member 'rcContext::m_timerEnabled'
recastnavigation\Recast\Include\Recast.h(392): warning C4820: 'rcContour': '1' bytes padding added after data member 'rcContour::area'
recastnavigation\Recast\Include\Recast.h(1075): warning C4365: 'return': conversion from 'unsigned int' to 'int', signed/unsigned mismatch
..\..\..\Recast\Source\RecastLayers.cpp(39): warning C4820: 'rcLayerRegion': '1' bytes padding added after data member 'rcLayerRegion::neis'
..\..\..\Recast\Source\RecastLayers.cpp(376): warning C4365: 'initializing': conversion from 'int' to 'unsigned short', signed/unsigned mismatch
..\..\..\Recast\Source\RecastLayers.cpp(376): warning C4365: 'initializing': conversion from 'int' to 'const unsigned short', signed/unsigned mismatch
..\..\..\Recast\Source\RecastLayers.cpp(396): warning C4365: 'argument': conversion from 'int' to 'const unsigned short', signed/unsigned mismatch
..\..\..\Recast\Source\RecastLayers.cpp(515): warning C4365: 'initializing': conversion from 'unsigned int' to 'int', signed/unsigned mismatch
..\..\..\Recast\Source\RecastLayers.cpp(515): warning C4365: 'initializing': conversion from 'unsigned int' to 'const int', signed/unsigned mismatch
..\..\..\Recast\Source\RecastLayers.cpp(517): warning C4365: 'argument': conversion from 'const int' to '::size_t', signed/unsigned mismatch
..\..\..\Recast\Source\RecastLayers.cpp(523): warning C4365: 'argument': conversion from 'const int' to '::size_t', signed/unsigned mismatch
..\..\..\Recast\Source\RecastLayers.cpp(525): warning C4365: 'argument': conversion from 'const int' to '::size_t', signed/unsigned mismatch
..\..\..\Recast\Source\RecastLayers.cpp(531): warning C4365: 'argument': conversion from 'const int' to '::size_t', signed/unsigned mismatch
..\..\..\Recast\Source\RecastLayers.cpp(533): warning C4365: 'argument': conversion from 'const int' to '::size_t', signed/unsigned mismatch
..\..\..\Recast\Source\RecastLayers.cpp(539): warning C4365: 'argument': conversion from 'const int' to '::size_t', signed/unsigned mismatch
..\..\..\Recast\Source\RecastLayers.cpp(611): warning C4365: 'initializing': conversion from 'int' to 'unsigned char', signed/unsigned mismatch
..\..\..\Recast\Source\RecastLayers.cpp(632): warning C4365: '=': conversion from 'int' to 'unsigned char', signed/unsigned mismatch
RecastMesh.cpp
recastnavigation\Recast\Include\Recast.h(174): warning C4820: 'rcContext': '2' bytes padding added after data member 'rcContext::m_timerEnabled'
recastnavigation\Recast\Include\Recast.h(392): warning C4820: 'rcContour': '1' bytes padding added after data member 'rcContour::area'
recastnavigation\Recast\Include\Recast.h(1075): warning C4365: 'return': conversion from 'unsigned int' to 'int', signed/unsigned mismatch
..\..\..\Recast\Source\RecastMesh.cpp(1029): warning C4365: 'argument': conversion from 'int' to '::size_t', signed/unsigned mismatch
..\..\..\Recast\Source\RecastMesh.cpp(1421): warning C4365: 'argument': conversion from 'int' to 'unsigned short', signed/unsigned mismatch
..\..\..\Recast\Source\RecastMesh.cpp(1444): warning C4365: 'initializing': conversion from 'int' to 'unsigned short', signed/unsigned mismatch
RecastMeshDetail.cpp
recastnavigation\Recast\Include\Recast.h(174): warning C4820: 'rcContext': '2' bytes padding added after data member 'rcContext::m_timerEnabled'
recastnavigation\Recast\Include\Recast.h(392): warning C4820: 'rcContour': '1' bytes padding added after data member 'rcContour::area'
recastnavigation\Recast\Include\Recast.h(1075): warning C4365: 'return': conversion from 'unsigned int' to 'int', signed/unsigned mismatch
RecastRasterization.cpp
recastnavigation\Recast\Include\Recast.h(174): warning C4820: 'rcContext': '2' bytes padding added after data member 'rcContext::m_timerEnabled'
recastnavigation\Recast\Include\Recast.h(392): warning C4820: 'rcContour': '1' bytes padding added after data member 'rcContour::area'
recastnavigation\Recast\Include\Recast.h(1075): warning C4365: 'return': conversion from 'unsigned int' to 'int', signed/unsigned mismatch
RecastRegion.cpp
recastnavigation\Recast\Include\Recast.h(174): warning C4820: 'rcContext': '2' bytes padding added after data member 'rcContext::m_timerEnabled'
recastnavigation\Recast\Include\Recast.h(392): warning C4820: 'rcContour': '1' bytes padding added after data member 'rcContour::area'
recastnavigation\Recast\Include\Recast.h(1075): warning C4365: 'return': conversion from 'unsigned int' to 'int', signed/unsigned mismatch
..\..\..\Recast\Source\RecastRegion.cpp(88): warning C4365: '=': conversion from 'int' to 'unsigned short', signed/unsigned mismatch
..\..\..\Recast\Source\RecastRegion.cpp(97): warning C4365: '=': conversion from 'int' to 'unsigned short', signed/unsigned mismatch
..\..\..\Recast\Source\RecastRegion.cpp(108): warning C4365: '=': conversion from 'int' to 'unsigned short', signed/unsigned mismatch
..\..\..\Recast\Source\RecastRegion.cpp(117): warning C4365: '=': conversion from 'int' to 'unsigned short', signed/unsigned mismatch
..\..\..\Recast\Source\RecastRegion.cpp(142): warning C4365: '=': conversion from 'int' to 'unsigned short', signed/unsigned mismatch
..\..\..\Recast\Source\RecastRegion.cpp(151): warning C4365: '=': conversion from 'int' to 'unsigned short', signed/unsigned mismatch
..\..\..\Recast\Source\RecastRegion.cpp(162): warning C4365: '=': conversion from 'int' to 'unsigned short', signed/unsigned mismatch
..\..\..\Recast\Source\RecastRegion.cpp(171): warning C4365: '=': conversion from 'int' to 'unsigned short', signed/unsigned mismatch
..\..\..\Recast\Source\RecastRegion.cpp(262): warning C4365: 'initializing': conversion from 'int' to 'unsigned short', signed/unsigned mismatch
..\..\..\Recast\Source\RecastRegion.cpp(423): warning C4365: '=': conversion from 'int' to 'unsigned short', signed/unsigned mismatch
..\..\..\Recast\Source\RecastRegion.cpp(467): warning C4365: '=': conversion from 'int' to 'unsigned short', signed/unsigned mismatch
..\..\..\Recast\Source\RecastRegion.cpp(534): warning C4820: 'rcRegion': '1' bytes padding added after data member 'rcRegion::connectsToBorder'
..\..\..\Recast\Source\RecastRegion.cpp(537): warning C4625: 'rcRegion': copy constructor was implicitly defined as deleted
..\..\..\Recast\Source\RecastRegion.cpp(537): warning C5026: 'rcRegion': move constructor was implicitly defined as deleted
..\..\..\Recast\Source\RecastRegion.cpp(537): warning C4626: 'rcRegion': assignment operator was implicitly defined as deleted
..\..\..\Recast\Source\RecastRegion.cpp(537): warning C5027: 'rcRegion': move assignment operator was implicitly defined as deleted
..\..\..\Recast\Source\RecastRegion.cpp(1390): warning C4365: 'argument': conversion from 'int' to 'unsigned short', signed/unsigned mismatch
..\..\..\Recast\Source\RecastRegion.cpp(1391): warning C4365: 'argument': conversion from 'int' to 'unsigned short', signed/unsigned mismatch
..\..\..\Recast\Source\RecastRegion.cpp(1392): warning C4365: 'argument': conversion from 'int' to 'unsigned short', signed/unsigned mismatch
..\..\..\Recast\Source\RecastRegion.cpp(1393): warning C4365: 'argument': conversion from 'int' to 'unsigned short', signed/unsigned mismatch
..\..\..\Recast\Source\RecastRegion.cpp(1565): warning C4365: 'initializing': conversion from 'int' to 'unsigned short', signed/unsigned mismatch
..\..\..\Recast\Source\RecastRegion.cpp(1580): warning C4365: 'argument': conversion from 'int' to 'unsigned short', signed/unsigned mismatch
..\..\..\Recast\Source\RecastRegion.cpp(1581): warning C4365: 'argument': conversion from 'int' to 'unsigned short', signed/unsigned mismatch
..\..\..\Recast\Source\RecastRegion.cpp(1582): warning C4365: 'argument': conversion from 'int' to 'unsigned short', signed/unsigned mismatch
..\..\..\Recast\Source\RecastRegion.cpp(1583): warning C4365: 'argument': conversion from 'int' to 'unsigned short', signed/unsigned mismatch
..\..\..\Recast\Source\RecastRegion.cpp(1591): warning C4365: '=': conversion from 'int' to 'unsigned short', signed/unsigned mismatch
..\..\..\Recast\Source\RecastRegion.cpp(1708): warning C4365: 'argument': conversion from 'int' to 'unsigned short', signed/unsigned mismatch
..\..\..\Recast\Source\RecastRegion.cpp(1709): warning C4365: 'argument': conversion from 'int' to 'unsigned short', signed/unsigned mismatch
..\..\..\Recast\Source\RecastRegion.cpp(1710): warning C4365: 'argument': conversion from 'int' to 'unsigned short', signed/unsigned mismatch
..\..\..\Recast\Source\RecastRegion.cpp(1711): warning C4365: 'argument': conversion from 'int' to 'unsigned short', signed/unsigned mismatch

```

**Comment by jakobbotsch** [comment] 2017-11-08 14:15
I am unable to reproduce the issue with your provided .gset. The terrain does not look like your exa

This issue used to happen when the detail mesh sampling sampled a span that was not walkable. This would happen because of edge simplification which would make some polygons go through terrain when the agent radius is very low (as in your example).

Most likely this is another case of #153 (you can see a similar situation happening in #151, which #153 was split out of).

However I do see that the .gset uses some very "extreme" settings. In general the lib is mostly tested of common "sane" settings, so I am not surprised that there might be issues with your particular configuration.

**Comment by LiamKarlMitchell** [comment] 2017-11-08 21:08
The gset+mesh is an example that has the problem. Just a chunk of the same mesh.

With agent radius (2.3), max edge error (1.5) and Max sample error (1) the problem appears to be gone.

It turns out the error's are not a bad thing as I had initially thought, they allow for smoothing in-between / not matching the input mesh exactly.

**Comment by jakobbotsch** [comment] 2018-01-05 11:47
I cannot reproduce it using your files. My steps are:
1. Extract .gset and .obj to Meshes folder
2. I choose Tile Mesh and select Broken7.gset
3. I press Build. I see no vertical polygons like in your screenshot.

Do you reproduce the problem using these steps?

**Comment by jakobbotsch** [comment] 2018-07-14 11:05
I am going to close this issue since I could not reproduce it. Please reopen if you can provide the steps to reproduce it.

**Closed by jakobbotsch** 2018-07-14 11:05 UTC
