### ISSUE TITLE
dtVlerp Crash in closestPointOnDetailEdges

### ISSUE THREAD

**Issue by redstorm-fyy** [recastnavigation/recastnavigation#394] opened 2019-05-28 03:33 UTC
If pd->triCount==0 then pmin,pmax will be null. 
Then dtVlerp will crash at DetourNavMesh.cpp:673

**Comment by jakobbotsch** [comment] 2019-05-28 20:20
Thanks, this is caused by #381. Though the problem is that such triangles should not exist in meshes. Can you see what `poly->vertCount` is for your case?

**Comment by redstorm-fyy** [comment] 2019-05-31 05:52
I made a mistake. My crash is not caused by pd->triCount==0 .
The log shows pd->triCount==12 and poly->vertCount==6.

**Comment by jakobbotsch** [comment] 2019-06-01 12:21
It is probably still crashing because of #381. If you are able to give us a short repro in the demo (cutout of your terrain and build settings), that would really help a lot.

**Comment by MaxHayman** [comment] 2021-01-21 18:55
Hello, I am getting this issue running off the latest. After #381 has been merged.

pd->triCount = 7

all get skipped due to this continue
```
	const int ANY_BOUNDARY_EDGE =
		(DT_DETAIL_EDGE_BOUNDARY << 0) |
		(DT_DETAIL_EDGE_BOUNDARY << 2) |
		(DT_DETAIL_EDGE_BOUNDARY << 4);
	if (onlyBoundary && (tris[3] & ANY_BOUNDARY_EDGE) == 0)
		continue;
```

I am guessing that my navmesh might be broken but it would be nice if this didnt cause a nullref xD

**Comment by MaxHayman** [comment] 2021-01-24 00:26
@jakobbotsch So is this a problem with my navmesh i have generated and not with the detour runtime? How can I ensure that my navmeshes are okay and dont crash at runtime? 

Thanks,
Max

**Comment by jakobbotsch** [comment] 2021-02-16 15:03
After looking at @MaxHayman's data, my guess is that the following check can fail for all edges due to lack of precision at large magnitudes:
https://github.com/recastnavigation/recastnavigation/blob/e75adf86f91eb3082220085e42dda62679f9a3ea/Recast/Source/RecastMeshDetail.cpp#L1141-L1154

So then the `DT_DETAIL_EDGE_BOUNDARY` flag is not reliable. I have suggested to @MaxHayman to scale their data so that it is closer to 0, but as a fix I think we can detect boundary edges when building detail meshes by looking at the hull rather than using a distance check. Something like https://github.com/recastnavigation/recastnavigation/compare/master...jakobbotsch:robust-detail-edges?expand=1.
@memononen any thoughts? It gives the same results on our test meshes and it is a bit faster too. Although for larger polygons it could probably be slower.

**Comment by jakobbotsch** [comment] 2021-02-16 15:04
@MaxHayman can you try using the branch I linked above and see if it solves the problem using your own settings?

**Comment by memononen** [comment] 2021-02-16 21:11
@jakobbotsch that looks good to me.

 I think the hull is always the `nhull` first indices and they are in ascending order, so I think you should be able to skip the whole array thing and use something like this:
```
static bool onHull(int a, int b, int nhull)
{
	if (a < nhull) {
		// a is part of the hull loop, if b is next consecutive index in the loop, the edge is part of the hull.
		const int next = (a + 1) % nhull;
		return b == next;
	}
	return false;
}
```

**Comment by jakobbotsch** [comment] 2021-02-16 21:41
It doesn't look like they are in ascending order, eg. this was the detail vertices of a poly, the original ones being P0 to P3:
![image](https://user-images.githubusercontent.com/7887810/108124910-feb42400-70a7-11eb-81e9-c41d64236f26.png)
But maybe it would be easy to change this actually, let me take a look tomorrow.

**Comment by memononen** [comment] 2021-02-17 19:13
Ah... right. The corners are first, because that allows to reuse the poly vertices there. Maybe then just checking that both a & b < nhull could speed things up a bit.

**Comment by jakobbotsch** [comment] 2021-02-17 19:29
> Ah... right. The corners are first, because that allows to reuse the poly vertices there. Maybe then just checking that both a & b < nhull could speed things up a bit.

Hmm, won't that detect an edge from P6 to P7 as being an edge on the hull?

I think the vertices are not actually reused between separate detail meshes, as far as I can tell, but changing the order is also problematic due to the first loop in `triangulateHull`:
https://github.com/recastnavigation/recastnavigation/blob/e75adf86f91eb3082220085e42dda62679f9a3ea/Recast/Source/RecastMeshDetail.cpp#L560-L583
I guess the indices of the original vertices could be tracked separately. Not sure if it is worth it, do you think so?

**Comment by memononen** [comment] 2021-02-17 20:55
The detail vertices which are also the corresponding polygon vertices are not stored. Like this:
```
const float* v[3];
for (int j = 0; j < 3; ++j)
{
	if (tris[j] < poly->vertCount)
		v[j] = &tile->verts[poly->verts[tris[j]] * 3];
	else
		v[j] = &tile->detailVerts[(pd->vertBase + (tris[j] - poly->vertCount)) * 3];
}
```

I meant to just use the `nhull` to detect if the edge is potentially part of the hull, then do the search like you had. This should early out quite a few edge tests:
```
static bool onHull(int a, int b, int nhull, int* hull)
{
	if (a >= nhull || b >= nhull)
		return false;

	for (int j = nhull - 1, i = 0; i < nhull; j = i++)
	{
		if (a == hull[j] && b == hull[i])
			return true;
	}

	return false;
}
```

**Comment by jakobbotsch** [comment] 2021-02-18 12:54
I see, the sharing is implemented in `dtCreateNavMeshData` using the indices indeed. Ok, I will add the early out you suggest then and keep the rest as it is.

**Comment by grahamboree** [comment] 2023-07-04 21:07
Hey @jakobbotsch, what's the status of this?

**Comment by jakobbotsch** [comment] 2023-08-10 20:43
@grahamboree Sorry about the late response, I forgot about it and needed the reminder in #656.
I honestly do not remember why I did not submit the PR. Very likely I wanted to run the patch over some large meshes first, but never got around to do that. Sadly I don't have any meshes lying around today, so I don't have a good way of testing it.

**Comment by grahamboree** [comment] 2023-08-10 21:12
@jakobbotsch not sure if this helps, but there's some fairly large exterior models here: https://casual-effects.com/data/  Specifically, the last one in the list "lumberyard bistro" is a high-poly chunk of a town that might be a good test case.  Not sure if these will stress things in the way you need though.

In general, it might be easier to submit the PR and then we can test and talk through it there?  Up to you.

**Closed** 2023-12-20 05:46 UTC
Labels: type: bug, area: Detour
