### ISSUE TITLE
inconsistent naming of height field type

### ISSUE THREAD

**Issue by wbierman** [recastnavigation/recastnavigation#161] opened 2016-01-19 08:27 UTC
Hello.

In some places, the naming for a height field is 'HeightField' and in others it is 'Heightfield'.  It would be a breaking change and require users update their code, but would allow for easier use of smart pointers.  For example:

```
#define SMART_PTR(x) using Smart##x = std::unique_ptr<rc##x, decltype(&rcFree##x>>
SMART_PTR(HeightField);
SMART_PTR(ContourSet);
// etc...
SmartHeightField heightField(...);
```

I would be happy to submit a pull request to change this, if it would be accepted.

**Comment by Janiels** [comment] 2016-01-19 09:51
I think we would be interested in this once we have semantic versioning set up so we can properly communicate breaking changes. Right now the API has been stable for a very long time so it should probably be released as our first major version first.

**Comment by namreeb** [comment] 2016-01-19 09:55
If you're talking about something so big, you might as well just implement proper classes with destructors.

**Comment by hymerman** [comment] 2016-01-19 10:04
It's annoying, that's true, but it's such a minor annoyance that I don't think we'd want it until there's some other breaking change that it can go alongside. I personally wouldn't write a macro to create smart pointer types like that anyway - and for people that would, it's not much effort to type it out in full.

I'm not sure whether to leave this issue around until after we've started versioning properly (so we don't forget about it), or to close it as "won't fix" (to avoid clogging up the list with stale issues). @Janiels, @grahamboree - what do you think we should do with this kind of thing?

**Comment by Janiels** [comment] 2016-01-19 10:10
@hymerman I agree. We have #120 right now as well, but not more than that, I believe. I'm not sure these two changes are enough to warrant a new major release, though.

We could tag it with a "Future" milestone and leave it -- I think that makes sense. In the future when we do want to release a new major version something like this should go in there, so this way we would not forget about it.

**Comment by wbierman** [comment] 2016-01-19 10:10
I didn't realize other people were contributing to this project now.  Nice to see it is being kept maintained.  With that in mind, if you are considering some future significant update to this codebase, perhaps a better solution would be to implement a proper destructor for some of these types?

The reason that using a smart pointer with the code as it is is nice is that the deallocators just so happen to conform to the prototype required by the deallocator parameter to std::unique_ptr<T> et al.  If it were a class with a destructor, you wouldn't need either the smart pointer nor the deallocation call.

**Comment by hymerman** [comment] 2016-01-19 18:01
I'd like to move things that way, yes, but I think the reason there are few 'proper classes' currently is that `memcpy`, `memset` and friends are used a lot, and this requires types have trivial layout :( We should still do it bit by bit, but probably alongside other rework.

**Comment by Janiels** [comment] 2016-01-19 19:48
R&D used to use destructors. It was changed when custom allocators were introduced in commit cd3a351f.
We could still use destructors that automatically call the correct free function. I suppose Mikko did it this way so the custom allocation was mirrored with a custom free. I have no strong feelings one way or the other, but I completely understand not mix-and-matching them.

**Comment by grahamboree** [comment] 2016-01-19 20:39
FWIW destructors and custom allocators are not mutually incompatible.  Problems arise when attempting to use the out-of-the-box C++11 pointer types and the related `std::make_shared` and `std::make_unique` style of creation with Recast objects.

Because we do all allocations through the `rcAlloc` family of functions, we don't use new and delete, so `std::make_*` will not work.  The STL solution to this is the `std::allocate_shared` style of creation, which allows for a custom allocator to be used.  Alternatively, you can create objects using the rcAlloc functions, and put the raw pointer in a `std::unique_ptr` passing a custom Deleter that calls the appropriate Recast-specific free function.  

There's a separate but related issue of us using `memset` in some alloc functions to initialize POD structs, where it'd be much more canonical and robust to use constructors and destructors for this purpose.  If anything changes in those structs that suddenly makes them non-POD, the memset is going to cause some real headaches.  Not using constructors and destructors also prevents the usage of smart pointers at all with these types.

**Comment by wbierman** [comment] 2016-01-19 21:39
> Not using constructors and destructors also prevents the usage of smart pointers at all with these types.

As I mentioned above, I am successfully using smart pointers with the current HEAD.  I assume it is just luck that the prototype of the deallocators is compatible as a STL smart pointer custom deleter.

Example:

```
using SmartHeightFieldPtr = std::unique_ptr<rcHeightfield, decltype(&rcFreeHeightField)>;
SmartHeightFieldPtr solid(rcAllocHeightfield(), rcFreeHeightField);
```

It works great.  But it sure would be cleaner if I could simply do:

```
rcHeightField solid;
```

**Comment by grahamboree** [comment] 2016-01-19 22:07
Yeah that last sentence is questionably worded.  :coffee: 

I guess I meant that if for some reason they become part of an inheritance hierarchy, it won't chain constructors or destructors properly.  You bring up another good point though, in that we cannot construct an instance of these classes without heap-allocating it through `rcAlloc`.  I'm not sure if this is causing any unnecessary heap allocations right now, but it has the potential to bite someone with uninitialized data.

**Comment by wbierman** [comment] 2016-01-19 22:22
Before I realized that I could use std::unique_ptr<T> for these types, I was stack-allocating them.  I would just memset() them to zero the way their individual constructors do.  Not the most elegant solution, either.

**Comment by grahamboree** [comment] 2016-01-19 22:41
I mean that base classes call parent class constructors, and destructors are automatically called in the reverse order of construction.  When you're manually writing the "free" function, you have to do this manually, rather than just letting the compiler do it for you.

The entire point of this is that constructors and destructors are meant for object initialization and de-initialization.  The fact that you're memset-ing a stack-allocated instance of this class is addressing the symptoms and not the cause.

**Comment by hymerman** [comment] 2016-01-19 22:41
It's not just inheritance; there is all sorts of stuff that makes `memset` an invalid thing to do on a type. I forget the exact term but I think the type has to have 'trivial layout'.

Anyway... I think we'd all agree that removing the per-type allocator functions (`dtAllocHeightField` etc), and instead giving those types proper constructors and destructors to allow them to sensibly be constructed on the stack, is a good idea. That doesn't prevent users from using the general `dtAlloc` etc. functions to hook heap allocations into their own memory allocators. And it's much easier to understand, and harder to use wrong.

It may prove to be slightly slower in some cases (e.g. where an array of items is `memset` at once - that's always going to be slower than calling the constructor/destructor of each element separately). I would like to have some automated tests (which report performance) in place before this, just so we can make an informed decision about what the performance impact would be of making such a change. Nothing too hardcore - it would just be nice to compare before and after running times for a few example levels.

**Comment by namreeb** [comment] 2016-01-19 22:55
I never intended to suggest that memset() was a good thing to be doing.  If you move to constructors, the initializer list will take care of what memset() had taken care of.

> It may prove to be slightly slower in some cases (e.g. where an array of items is memset at once - that's always going to be slower than calling the constructor/destructor of each element separately).

I don't think it would be significant.  And people could replace the default allocator with calloc() if they choose.

**Comment by wbierman** [comment] 2016-01-19 22:56
I never intended to suggest that memset() was a good thing to be doing. If you move to constructors, the initializer list will take care of what memset() had taken care of.

> It may prove to be slightly slower in some cases (e.g. where an array of items is memset at once - that's always going to be slower than calling the constructor/destructor of each element separately).

I don't think it would be significant. And people could replace the default allocator with calloc() if they choose.

**Comment by hymerman** [comment] 2016-01-19 23:12
I'd prefer "I have measured it and it isn't significant" to "I don't think it would be significant" :)

Sweeping changes like "altering the way all objects are allocated" scare me now that I'm a library maintainer rather than a developer with one specific set of levels I can check - some automated tests with real-world data would put me at ease for sure!

**Comment by wbierman** [comment] 2016-01-20 04:54
Well those two statements mean different things.  But I wrote a small .cpp and these are the results:

Visual Studio 2015 (no optimizations):

> Initializer list via stack allocation took 1.25165 seconds for 50000000 iterations
> memset(0) via stack allocation took 1.48693 seconds for 50000000 iterations

clang 3.4.1 on FreeBSD (no optimizations):
> Initializer list via stack allocation took 0.429578 seconds for 50000000 iterations
> memset(0) via stack allocation took 1.31279 seconds for 50000000 iterations

g++ 4.8.4 on Ubuntu (no optimizations):
> Initializer list via stack allocation took 0.313623 seconds for 50000000 iterations
> memset(0) via stack allocation took 0.264579 seconds for 50000000 iterations

Here is the code:
```
#include <cstring>
#include <iostream>
#include <chrono>

#define ITERATIONS 50000000
#define INITIALIZER_LIST

class MyClass
{
    private:
        int m_int0;
        int m_int1;
        int m_int2;
        int m_int3;
        int m_int4;
        int m_int5;
        int m_int6;
        int m_int7;
        int m_int8;
        int m_int9;
    public:
        MyClass()
#ifdef INITIALIZER_LIST
            : m_int0(0), m_int1(0), m_int2(0), m_int3(0), m_int4(0), m_int5(0), m_int6(0), m_int7(0), m_int8(0), m_int9(0) {}
#else
        {
            memset(this, 0, sizeof(MyClass));
        }
#endif
};

int main()
{
    auto const start = std::chrono::high_resolution_clock::now();

    for (auto i = 0; i < ITERATIONS; ++i)
        volatile MyClass instance;

    auto const stop = std::chrono::high_resolution_clock::now();
    auto const duration = std::chrono::duration_cast<std::chrono::duration<double>>(stop - start);

    std::cout <<
#ifdef INITIALIZER_LIST
        "Initializer list"
#else
        "memset(0)"
#endif
        << " via stack allocation took " << duration.count() << " seconds for " << ITERATIONS << " iterations" << std::endl;

    return 0;
}
```

**Comment by hymerman** [comment] 2016-01-20 09:06
I think you've misunderstood what I'm saying; I'm not asking for a comparison of memset vs. initializer lists within a constructor, I'm saying that adding constructors and destructors to types that currently don't have them can prevent code like this which is used all over the library:

    	memset(m_tiles, 0, sizeof(dtMeshTile)*m_maxTiles);

Replacing that with a loop to construct `m_maxTiles` tiles individually is likely to be slower. I don't know if it will or it won't until I measure it, but my 'gut feeling' is that it will be slower. That's not the end of the world of course - there are more factors to consider than just runtime performance, such as maintainability and robustness, so we may still want to do the change.

The other part of what I'm saying is that I would like to have performance tests in place *before* doing any work on this, which measure *real world* cases so we can measure the impact of any change.

**Comment by hymerman** [comment] 2016-01-20 09:07
Just to be clear, I'm not asking you to create any benchmarks - we'll create those at some point, and after that's done we'll look at requests like this again.

**Comment by wbierman** [comment] 2016-01-20 10:29
Ah, I see.  Yes, it probably would be slower.  I will revert to my original statement which is that I do not believe the performance hit would be significant.

**Comment by grahamboree** [comment] 2023-07-05 00:50
Closing this as it's turned into a lot of C++ bikeshedding.  Moved the original naming issue to #643

**Closed by grahamboree** 2023-07-05 00:50 UTC
Labels: type: enhancement
